name: Lint

on:
  pull_request:
     branches: ['**']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Run Linter
        run: npm run lint